# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20160524_1224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(default=-1),
        ),
    ]
