# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 16, 37, 44, 798543)),
        ),
    ]
