# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_profile_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='registered_at',
        ),
    ]
